name: Docker Build and Release
on: [ push ]
env:
  APP_NAME: "pet-clinic-test123"
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        cache: maven
    - name: Compile, build and push
      run: |
        heroku container:login 
        mvn package
        docker build --tag registry.heroku.com/${APP_NAME}/web -f Dockerfile .
        docker push registry.heroku.com/${APP_NAME}/web
    - name: Release
      run: |
        heroku container:login 
        heroku stack:set container --app ${APP_NAME}
        heroku container:release web --app ${APP_NAME}
